{
 "title": "AgroTech Monitor 🚜",
 "time": { "from": "2026-01-28T01:13:10.988Z", "to": "2026-01-28T01:13:21.386Z" },
 "templating": {
  "list": [
   {
    "name": "field_name",
    "label": "Talhão",
    "query": {
     "query": "label_values(agro_temperature_celsius{property_name=\"$property_name\"}, field_name)"
    }
   },
   {
    "name": "farmer_name",
    "label": "Fazendeiro",
    "query": {
     "query": "label_values(agro_temperature_celsius, farmer_name)"
    }
   },
   {
    "name": "property_name",
    "label": "Propriedade",
    "query": {
     "query": "label_values(agro_temperature_celsius{farmer_name=\"$farmer_name\"}, property_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "New panel",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "# Prioridade 4: Tempestade (Se pressão < 1000, retorna 4)\r\n(agro_pressure_hpa{field_name=~\"$field_name\"} < 1000) * 0 + 4\r\nor\r\n# Prioridade 3: Calor (Se temp > 35, retorna 3)\r\n(agro_temperature_celsius{field_name=~\"$field_name\"} > 35) * 0 + 3\r\nor\r\n# Prioridade 2: Geada (Se temp < 5, retorna 2)\r\n(agro_temperature_celsius{field_name=~\"$field_name\"} < 5) * 0 + 2\r\nor\r\n# Prioridade 1: Seca (Se umidade < 30, retorna 1)\r\n(agro_soil_humidity_percent{field_name=~\"$field_name\"} < 30) * 0 + 1\r\nor\r\n# Prioridade 0: Normal (Pega qualquer métrica existente, zera e retorna 0)\r\n(agro_temperature_celsius{field_name=~\"$field_name\"} * 0)",
     "legendFormat": "{{field_name}}"
    }
   ]
  },
  {
   "title": "🌡️ Temperatura em Tempo Real",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "agro_temperature_celsius{farmer_name=\"$farmer_name\", property_name=\"$property_name\", field_name=~\"$field_name\"}",
     "legendFormat": "Talhão {{field_name}}"
    }
   ]
  },
  {
   "title": "💧 Umidade do Solo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "expr": "agro_soil_humidity_percent{farmer_name=\"$farmer_name\", property_name=\"$property_name\", field_name=~\"$field_name\"}",
     "legendFormat": "Talhão {{field_name}}"
    }
   ]
  },
  {
   "title": "Alertas de Seca",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ceil(sum by (field_name) (increase(agro_alert_drought_total{field_name=~\"$field_name\"}[1h]))) or (max by (field_name) (agro_soil_humidity_percent{field_name=~\"$field_name\"}) * 0)",
     "legendFormat": "{{field_name}}"
    }
   ]
  },
  {
   "title": "Alertas de Geada",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ceil(sum by (field_name) (increase(agro_alert_frost_total{field_name=~\"$field_name\"}[1h]))) or (max by (field_name) (agro_temperature_celsius{field_name=~\"$field_name\"}) * 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "☁️ Pressão em Tempo Real",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "expr": "agro_pressure_hpa{farmer_name=\"$farmer_name\", property_name=\"$property_name\", field_name=~\"$field_name\"}",
     "legendFormat": "Talhão {{field_name}}"
    }
   ]
  },
  {
   "title": "Alertas de tempestade",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ceil(sum by (field_name) (increase(agro_alert_storm_total{field_name=~\"$field_name\"}[1h]))) or (max by (field_name) (agro_pressure_hpa{field_name=~\"$field_name\"}) * 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alertas onda de calor",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ceil(sum by (field_name) (increase(agro_alert_heat_total{field_name=~\"$field_name\"}[1h]))) or (max by (field_name) (agro_temperature_celsius{field_name=~\"$field_name\"}) * 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "⚡ Velocidade de Processamento (RPM)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(agro_events_processed_total[1m]) * 60",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}